### ISSUE TITLE
Radio-type inputs are being filtered improperly

### ISSUE THREAD

**Issue by rksiazek** [michalkoziara/Internet-Applications#3]
At https://github.com/michalkoziara/Internet-Applications/blob/e908c65a5ac19ff9473747f6d801c66e9d7bec48/funkcje.php#L122

As far as checkbox inputs are concerned, it is obvious to filter whether the received input's value has the array type.
But, when it comes to filter **radios** you can't go this way, as radios returns single strings instead of arrays.

**Comment by michalkoziara** [comment]
Changed type as suggested.
